services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redispassword
      - REDIS_PORT=6379
